### ISSUE TITLE
Distrobox using podman by default

### ISSUE THREAD

**Issue by kapi117** [agh-space-systems-rover/kalman_ws#1]
When trying to run `./scripts/distrobox` distrobox couldn't pull the image from docker, trying to pull from podman.

**SOLUTION**
Set environment variable `export DBX_CONTAINER_MANAGER="docker"`

**Comment by rayferric** [comment]
Suggested fix will be included in 0886dc2fce80a17189f99c98524769e9a258c926 @ [rework](https://github.com/agh-space-systems-rover/kalman_ws/tree/rework)
